pipelines:
  branches:
    main:
      - step:
          name: Build & Push Docker Image
          runs-on:
            - self.hosted
            - linux
          services: [ docker ]
          script:
            - echo "Building & pushing Docker image..."
            - docker build -t pepewee/soportetic-openia:$VERSION .
            - docker tag pepewee/soportetic-openia:$VERSION pepewee/soportetic-openia:latest
            - echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USER --password-stdin
            - docker push pepewee/soportetic-openia:$VERSION
            - docker push pepewee/soportetic-openia:latest

      - step:
          name: Deploy to Server
          runs-on:
            - self.hosted
            - linux
          script:
            - pipe: atlassian/ssh-run:0.4.3
              variables:
                SSH_USER: "$SSH_USER"
                SERVER:   "$SSH_HOST"
                SSH_KEY:  "$SSH_KEY"
                COMMAND: |
                  echo "Deploy to server..."
                  echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USER --password-stdin
                  docker pull pepewee/soportetic-openia:latest
                  docker-compose -f /data/sites/ia-sp-backoffice.ucatolica.cue.ec/html/IA/docker-compose.yml down
                  docker-compose -f /data/sites/ia-sp-backoffice.ucatolica.cue.ec/html/IA/docker-compose.yml up -d

