version: "3.9"

services:
  whatsapp_assistant:
    container_name: catia-assistant
    image: pepewee/soportetic-openia:latest
    # platform: linux/amd64
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      PYTHONPATH: /app/src
    restart: always
    volumes:
      - IA_Logs:/app/logs
    networks:
      - virtual_assistant_network

volumes:
  IA_Logs:

networks:
  virtual_assistant_network:
    external: true