version: "3.9"

services:
  ia-soporte:
    container_name: ia-soporte-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=development  # 🔥 Modo Desarrollo
    restart: always
    volumes:
      - .:/app  # 🔥 Bind mount para hot-reload
    networks:
      - virtual_assistant_network
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000", "--debug", "--reload"]

networks:
  virtual_assistant_network:
    external: true
