# Usa una imagen ligera de Python
FROM python:3.9-slim

# Define el directorio de trabajo
WORKDIR /app

# Copia solo el archivo de dependencias
COPY requirements.txt /app/requirements.txt

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install flask watchdog

ENV PYTHONPATH=/app
ENV FLASK_APP=src/app.py
ENV PYTHONUNBUFFERED=1

# Copia el resto del código fuente
COPY . /app

# Expone el puerto 5000
EXPOSE 5000

# Comando para desarrollo (Flask con hot-reload)
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000", "--debug"]
