version: "3.9"

services:
  ia-soporte:
    container_name: ia-soporte
    image: pepewee/soportetic-openia:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=production  # 🔥 Modo Producción
    restart: always
    volumes:
      - IA_Logs:/app/logs
    networks:
      - virtual_assistant_network

volumes:
  IA_Logs:
networks:
  virtual_assistant_network:
    external: true
