version: "3.9"

services:
  IA-Soporte:
    container_name: IA-Soporte
    image: pepewee/soportetic-openia:latest
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - IASoporte:/app
    restart: always
    networks:
      - virtual_assistant_network

volumes:
  IASoporte: 
networks:
  virtual_assistant_network:
    external: true
